// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PersonsDbContext))]
    partial class PersonsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryID = new Guid("d9c7b5a1-1234-4abc-8def-123456789001"),
                            CountryName = "USA"
                        },
                        new
                        {
                            CountryID = new Guid("d9c7b5a1-1234-4abc-8def-123456789002"),
                            CountryName = "Nepal"
                        },
                        new
                        {
                            CountryID = new Guid("d9c7b5a1-1234-4abc-8def-123456789003"),
                            CountryName = "India"
                        },
                        new
                        {
                            CountryID = new Guid("d9c7b5a1-1234-4abc-8def-123456789004"),
                            CountryName = "UK"
                        },
                        new
                        {
                            CountryID = new Guid("d9c7b5a1-1234-4abc-8def-123456789005"),
                            CountryName = "Canada"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("ReceiveNewsLetter")
                        .HasColumnType("bit");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("a1b2c3d4-1234-4abc-8def-123456789001"),
                            Address = "123 Main St, New York, NY",
                            CountryId = new Guid("d9c7b5a1-1234-4abc-8def-123456789001"),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            Gender = "Male",
                            Name = "John Doe",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            PersonId = new Guid("a1b2c3d4-1234-4abc-8def-123456789002"),
                            Address = "456 Oak Ave, Toronto, ON",
                            CountryId = new Guid("d9c7b5a1-1234-4abc-8def-123456789005"),
                            DateOfBirth = new DateTime(1992, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            Gender = "Female",
                            Name = "Jane Smith",
                            ReceiveNewsLetter = false
                        },
                        new
                        {
                            PersonId = new Guid("a1b2c3d4-1234-4abc-8def-123456789003"),
                            Address = "789 MG Road, Mumbai",
                            CountryId = new Guid("d9c7b5a1-1234-4abc-8def-123456789003"),
                            DateOfBirth = new DateTime(1988, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "raj.patel@example.com",
                            Gender = "Male",
                            Name = "Raj Patel",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            PersonId = new Guid("a1b2c3d4-1234-4abc-8def-123456789004"),
                            Address = "10 Downing St, London",
                            CountryId = new Guid("d9c7b5a1-1234-4abc-8def-123456789004"),
                            DateOfBirth = new DateTime(1995, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.watson@example.com",
                            Gender = "Female",
                            Name = "Emily Watson",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            PersonId = new Guid("a1b2c3d4-1234-4abc-8def-123456789005"),
                            Address = "Basantapur, Kathmandu",
                            CountryId = new Guid("d9c7b5a1-1234-4abc-8def-123456789002"),
                            DateOfBirth = new DateTime(1993, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sita.sharma@example.com",
                            Gender = "Female",
                            Name = "Sita Sharma",
                            ReceiveNewsLetter = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
